const getPrescriptionEmailTemplate = (patientName, prescriptionToken, frontendUrl) => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        body { 
          font-family: Arial, sans-serif; 
          line-height: 1.6; 
          color: #333; 
          margin: 0; 
          padding: 0; 
          background-color: #f4f4f4;
        }
        .container { 
          max-width: 600px; 
          margin: 20px auto; 
          background-color: #ffffff;
          border-radius: 8px;
          overflow: hidden;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .header { 
          background-color: #2563eb; 
          color: white; 
          padding: 30px 20px; 
          text-align: center; 
        }
        .header h1 { 
          margin: 0; 
          font-size: 28px; 
        }
        .content { 
          padding: 30px 20px; 
        }
        .content h2 {
          color: #2563eb;
          margin-top: 0;
        }
        .button { 
          display: inline-block; 
          padding: 14px 28px; 
          background-color: #2563eb; 
          color: white; 
          text-decoration: none; 
          border-radius: 5px; 
          margin: 20px 0; 
          font-weight: bold;
        }
        .button:hover {
          background-color: #1d4ed8;
        }
        .qr-section { 
          text-align: center; 
          padding: 25px; 
          background-color: #f9f9f9; 
          margin: 25px 0; 
          border-radius: 8px;
          border: 2px dashed #2563eb;
        }
        .qr-section img {
          width: 200px;
          height: 200px;
          border: 4px solid white;
          border-radius: 8px;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        .info-box {
          background-color: #eff6ff;
          border-left: 4px solid #2563eb;
          padding: 15px;
          margin: 20px 0;
          border-radius: 4px;
        }
        .footer { 
          text-align: center; 
          padding: 20px; 
          color: #666; 
          font-size: 12px; 
          background-color: #f9f9f9;
          border-top: 1px solid #e5e5e5;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>MedConnect+</h1>
          <p style="margin: 10px 0 0 0; font-size: 18px;">Your Medical Prescription</p>
        </div>
        <div class="content">
          <h2>Hello ${patientName},</h2>
          <p>Your prescription has been generated by your doctor and is ready for you.</p>
          
          <div class="info-box">
            <strong>📎 Your prescription PDF is attached to this email.</strong>
            <p style="margin: 10px 0 0 0; font-size: 14px;">You can download and save it for your records.</p>
          </div>

          <p><strong>Scan the QR code below</strong> to view your prescription online:</p>
          
          <div class="qr-section">
            <img src="cid:qrCode" alt="Prescription QR Code" />
            <p style="margin-top: 15px; color: #666; font-size: 14px;">
              Scan this QR code with your phone camera to view your prescription
            </p>
          </div>

          <p style="text-align: center;">
            <a href="${frontendUrl}/patient/prescriptions/qr/${prescriptionToken}" class="button">
              View Prescription Online
            </a>
          </p>

          <p style="margin-top: 30px;">If you have any questions about your prescription, please contact the hospital or your doctor.</p>
          
          <p style="margin-top: 20px;">
            Best regards,<br>
            <strong>MedConnect+ Team</strong>
          </p>
        </div>
        <div class="footer">
          <p>This is an automated email from MedConnect+ Hospital Management System.</p>
          <p>Please do not reply to this email.</p>
        </div>
      </div>
    </body>
    </html>
  `;
};

module.exports = {
  getPrescriptionEmailTemplate
};

